<script setup>
import { ref, computed, onMounted, onUnmounted, defineProps, reactive } from 'vue'
import axios from 'axios';
import { onClickOutside } from '@vueuse/core'
import PlaylistCreation from './PlaylistCreation.vue';
import { sharedState } from '@/sharedState.js'; // Shared states (aka global variables)
import PulseLoader from 'vue-spinner/src/PulseLoader.vue';

// Icons
import uploadIcon from '/src/assets/icons/svg-icons/upload-icon.svg'
import clipboardIcon from '/src/assets/icons/svg-icons/clipboard-icon.svg'
import autoGeneratedIcon from '/src/assets/icons/svg-icons/auto-generated-icon.svg'
import arrowDown from '/src/assets/icons/svg-icons/thin-chevron-arrow-bottom-icon.svg'

// Icons 2
import playIcon from '/src/assets/icons/video-player/play-icon.png'
import pauseIcon from '/src/assets/icons/video-player/pause-icon.png'
import fullSpeakerIcon from '/src/assets/icons/video-player/full-speaker-icon.png'
import muteSpeakerIcon from '/src/assets/icons/video-player/mute-speaker-icon.png'
import fullScreenIcon from '/src/assets/icons/video-player/fullscree-icon.png'

// Receiving the props:
const props = defineProps({
    formData: Object
});

// Edit Video Title Management

const videoTitleLength = computed(() => props.formData.details.title.length)
const userAbleToSave = computed(() => { // User can only save the information if the title`s length is equal or greater than 0
    return (props.formData.details.title.length > 0 ? true : false)
})

// Edit Video Description Management
const videoDescriptionLength = computed(() => {
    if (props.formData.details.description) {
        return props.formData.details.description.length
    } else {
        return 0
    }
})

// Playlist visibility options
const isPlaylistSelectionOpen = ref(false)
const togglePlaylistSelection = () => isPlaylistSelectionOpen.value = !isPlaylistSelectionOpen.value

const playlistIsLoading = ref(false)
let playlists = ref([])
const retrieveAllUserPlaylists = async () => {
    playlistIsLoading.value = true
    await axios.get('http://127.0.0.1:8000/studio/playlist/list', {
        params: {
            user_session_id: sessionStorage.getItem("user_session_id")
        }
    }).then((response) => {
        playlists.value = response.data.playlists;
    }).catch((error) => {
        console.log(error);
    }).finally(() => {
        playlistIsLoading.value = false;
    })
}

// Managing playlist creation tab with sharedStates
const togglePlaylistCreation = () => sharedState.isPlaylistCreationOpen.open = !sharedState.isPlaylistCreationOpen.open

const isAgeRestrictionOpen = ref(false)
const toggleAgeRestriction = () => {
    isAgeRestrictionOpen.value = !isAgeRestrictionOpen.value
}

// Video Management
const videoRef = ref(null) // The video tag itself
const videoDuration = ref(10.026666) // In Seconds
const videoCurrentTime = ref(0) // In seconds
const videoCurrentTimePercentage = ref(videoCurrentTime.value * 100 / videoDuration.value)
const video_current_label = ref('0:00')
const video_end_label = ref('0:00')
const videoTimeTracker = ref(null)
const videoTimeTrackerDisplay = ref('flex')

const divmod = (num1, num2) => [Math.floor(num1 / num2), num1 % num2]
const formatTime = (unit) => unit < 10 ? `0${unit}` : unit
const calculateTime = (duration) => { // Duration must be in seconds
    const [hours, remianingSeconds] = divmod(duration, 3600)
    const [minutes, seconds] = divmod(remianingSeconds, 60)
    if (hours) {
        return `${hours}:${formatTime(Math.round(minutes))}`
    } else {
        return `${Math.round(minutes)}:${formatTime(Math.round(seconds))}`
    }
}

const videoUpdate = (event) => { // When you click on a certain part of the video
    const videoProgressTime = event.target.value // The value of the input field
    const videoCurrentTime = (videoProgressTime * videoDuration.value) / 100
    videoRef.value.currentTime = videoCurrentTime
    video_current_label.value = calculateTime(videoCurrentTime) // Current Time label
    video_end_label.value = calculateTime(videoRef.value.duration) // End Time label
}

const videoProgress = (event) => { // Progressing the video-track-bar when you play the video
    videoCurrentTime.value = event.target.currentTime;
    videoCurrentTimePercentage.value = (videoCurrentTime.value * 100) / videoDuration.value;
    video_current_label.value = calculateTime(videoCurrentTime.value)
    video_end_label.value = calculateTime(videoRef.value.duration)
}

// Play and Pause the video
const isVideoPlayed = ref(false)
const toggleVideoPlay = () => {
    isVideoPlayed.value = !isVideoPlayed.value
    isVideoPlayed.value ? videoRef.value.play() : videoRef.value.pause()
}

// Fullscreen the video
const toggleVideoFullscreen = () => {
    videoRef.value.requestFullscreen()
}

// Mute and UnMute the video
const isVideoMuted = ref(false)
const toggleVideoMute = () => {
    isVideoMuted.value = !isVideoMuted.value
    videoRef.value.muted = isVideoMuted.value
}

// Video Volume (audio) Management
let defaultVideoVolume = ref(0.5) // between 0 and 1
const changeVideoVolume = (event) => {
    defaultVideoVolume.value = (event.target.value / 10); // The given value is between 0 and 100 but we need sth between 0 and 1
}

const currentTimeLabel = ref("0:00");
const trackerPosition = ref(4);
const updateTimeLabel = (event) => {
    const timeTracker = document.querySelector(".video-time-tracker");
    const { left, width } = timeTracker.getBoundingClientRect();

    // Calculate the position as a percentage
    const positionPercentage = Math.round(((event.clientX - left) * 100) / width);
    let duration = (positionPercentage / 100) * videoRef.value.duration
    currentTimeLabel.value = calculateTime(duration)

    // Update the tracker position
    const trackerWidth = 32;
    const halfTrackerWidth = trackerWidth / 2;
    const calculatedPosition = (event.clientX - left) - halfTrackerWidth + 9;
    trackerPosition.value = Math.max(4, Math.min(calculatedPosition, width));
};

const playlistSelectionContainer = ref(null)
onClickOutside(playlistSelectionContainer, () => {
    isPlaylistSelectionOpen.value = false
})

const thumbnailPictureInput = ref(null)
const thumbnailPictureSrc = ref(props.formData.thumbnailFile)
const uploadThumbnailPic = (event) => {
    const file = event.target.files[0];
    if (file) {
        props.formData.thumbnailFile = file;
        thumbnailPictureSrc.value = URL.createObjectURL(file);
    }
}

const thumbnailCanvas = ref(null)
const autoGenerateButton = ref(null)
const autoGenerateThumbnail = () => {
    const randomNum = Math.floor(Math.random() * 100); // Number between 0 and 100
    const randomTime = Math.floor((randomNum * videoRef.value.duration) / 100);

    // Create a hidden video element
    const hiddenVideo = document.createElement("video");
    hiddenVideo.src = videoRef.value.src; // Copying the source of the video

    // Get the canvas and context
    const canvas = thumbnailCanvas.value;
    const context = canvas.getContext("2d");
    context.drawImage(hiddenVideo, 0, 0, canvas.width, canvas.height);

    hiddenVideo.addEventListener('loadeddata', () => {
        hiddenVideo.currentTime = randomTime; // Seek to the random time
    });

    hiddenVideo.addEventListener('seeked', () => {
        context.drawImage(hiddenVideo, 0, 0, canvas.width, canvas.height);
        const dataUrl = canvas.toDataURL();
        const button = autoGenerateButton.value
        button.style.backgroundImage = `url(${dataUrl})`;
        button.style.backgroundSize = 'cover';
        button.style.backgroundPosition = 'center';
    });

    // Load the video
    hiddenVideo.load();
};


onMounted(() => {
    if (videoRef.value) videoRef.value.addEventListener('timeupdate', videoProgress);
})
onUnmounted(() => {
    if (videoRef.value) {
        videoRef.value.removeEventListener('timeupdate', videoProgress);
        video_end_label.value = calculateTime(videoRef.value.duration);
    }
});
</script>
<template>
    <div style="scrollbar-width: thin;" class="video-metadata-editor w-full max-h-[425px] h-auto flex
         flex-col pl-[50px] overflow-y-auto overflow-x-hidden">
        <div class="editor-title-header w-full h-[32px] mt-2 mb-4">
            <h1 class="text-[25px] font-semibold">Details</h1>
        </div>
        <div class="flex flex-row">
            <div class="flex flex-col h-auto max-w-[536px] mr-6">
                <div class="video-title w-[536px] h-[79px] rounded-lg border border-solid border-[#d6d6d6] hover:border-black hover:border-2
                         focus:border-2 relative pl-2 pt-2 flex flex-col mb-8"
                    :style="{ borderColor: userAbleToSave ? 'black' : 'red', borderWidth: !userAbleToSave ? '2px' : '1px' }">
                    <span class="text-[12px] font-medium text-gray-600">Title (required)</span>
                    <textarea v-model="formData.details.title"
                        class="mt-1 edit-title-input w-[440px] h-[41px] outline-none text-[15px] font-normal overflow-hidden leading-4"
                        placeholder="Add title" minlength="1" required maxlength="100"></textarea>
                    <span class="text-[12px] font-normal absolute right-1 bottom-1 text-gray-700"><span
                            class="title-char-counter">{{ videoTitleLength }}</span>/100</span>
                </div>
                <div class="video-description-1 w-[536px] flex flex-col max-w-[536px] relative h-[163px] max-h-[163px] rounded-lg
                        border border-[#d6d6d6] pl-2 pt-2 hover:border-black hover:border-2">
                    <span class="text-[12px] font-medium text-gray-600">Description</span>
                    <textarea style="scrollbar-width: thin;" v-model="formData.details.description"
                        class="mt-1 edit-title-input w-[440px] h-[151px] outline-none text-[15px] font-normal overflow-y-auto leading-4"
                        placeholder="Add description" maxlength="5000"></textarea>
                    <span class="text-[12px] font-normal absolute right-1 bottom-1 text-gray-700"><span
                            class="title-char-counter">{{ videoDescriptionLength }}</span>/5000</span>
                </div>
                <div class="thumbnail-container flex flex-col gap-y-1 mt-4">
                    <p class="text-[15px] font-medium">Thumbnail</p>
                    <span class="text-[13px] font-normal text-gray-600">Set a thumbnail that stands out and draws
                        viewers' attention.</span>
                    <div class="flex flex-row gap-x-4">
                        <button @click="thumbnailPictureInput.click()" class="w-[151px] h-[82px] rounded-sm border-dotted
                         cursor-pointer hover:border-black border-2 flex justify-center items-center flex-col gap-y-2">
                            <img class="w-[18px] h-[18px]" :src="uploadIcon" alt="">
                            <span class="text-[12px] font-normal">Upload file</span>
                            <input @change="uploadThumbnailPic" class="hidden" ref="thumbnailPictureInput" type="file">
                        </button>
                        <button ref="autoGenerateButton" @click="autoGenerateThumbnail" class="bg-transparent w-[151px] h-[82px]
                            rounded-sm border-dotted cursor-pointer hover:border-black
                             border-2 flex justify-center items-center flex-col gap-y-2">
                            <img class="w-[18px] h-[18px]" :src="autoGeneratedIcon" alt="">
                            <span class="text-[12px] font-normal">Auto-generated</span>
                        </button>
                        <button v-if="thumbnailPictureSrc || formData.thumbnailFile"
                            @click="thumbnailPictureInput.click()" class="w-[151px] h-[82px] rounded-sm border-dotted cursor-pointer hover:border-black border-2 flex
                             justify-center items-center flex-col gap-y-2"
                            :style="{ backgroundImage: `url(${thumbnailPictureSrc})`, backgroundSize: 'cover', backgroundRepeat: 'no-repeat' }">
                        </button>
                        <canvas ref="thumbnailCanvas" class="hidden" width="151" height="82"></canvas>
                        <img v-if="formData.details.thumbnail_url" :src="formData.details.thumbnail_url" class="w-[151px] h-[82px] border-2 hover:border-black cursor-pointer">
                    </div>
                </div>
                <div class="playlist-division flex flex-col gap-y-2 mt-4">
                    <p class="text-[15px] font-medium">Playlists</p>
                    <span class="text-[13px] font-normal text-gray-600">Add your video to one or more playlists to
                        organize your content for viewers.</span>
                    <div @click="togglePlaylistSelection(), retrieveAllUserPlaylists()" class="z-0 w-[260px] h-[48px]
                     rounded-lg border hover:border-black bg-white text-[15px]
                        font-normal relative cursor-pointer text-gray-600 pl-3 flex justify-start items-center">
                        <p>Select</p>
                        <button class="w-[12px] h-[12px] justify-self-end ml-auto mr-3">
                            <img class="w-full h-full" :src="arrowDown" alt="">
                        </button>
                    </div>
                    <div ref="playlistSelectionContainer"
                        v-if="isPlaylistSelectionOpen || sharedState.isPlaylistCreationOpen.open" class="absolute bottom-0 left-60
                             bg-white z-10 w-[397px] h-[389px] rounded-xl"
                        style="box-shadow: 0 0 10px rgba(0, 0, 0, 0.135);">
                        <div v-if="!playlistIsLoading" class="playlist-checkbox-group w-full h-[336px] flex flex-col gap-y-4 justify-start
                         items-start pl-4 pt-4">
                            <div v-for="(playlist, index) in playlists" :key="index" class="playlist1 w-[96%] hover:bg-[#e8e8e8] cursor-pointer h-[40px] border rounded-lg
                             flex items-center justify-start pl-2">
                                <router-link>
                                    <h3>{{ playlist.title }}</h3>
                                </router-link>
                                <p class="ml-auto text-[14px] font-normal">Visibility: {{ playlist.visibility }}</p>
                                <input :checked="playlist.id in formData.details.playlists" name="select_playlist"
                                    :value="playlist.id" v-model="formData.details.playlists" type="checkbox"
                                    class="ml-auto mr-2 text-[14px] font-normal">
                            </div>
                        </div>
                        <div v-else class="h-full flex justify-center items-center">
                            <PulseLoader size="18px" color="red"></PulseLoader>
                        </div>
                        <div class="action-buttons w-full h-[52.8px] text-black flex flex-row text-[14px] font-medium
                                 px-2 border-t items-center">
                            <button @click="togglePlaylistCreation"
                                class="rounded-3xl w-[120px] h-[36px] bg-[#f2f2f2] hover:bg-[#e5e5e5] flex justify-center items-center">
                                <span>Create playlist</span>
                            </button>
                            <Teleport v-if="sharedState.isPlaylistCreationOpen.open" to="body">
                                <PlaylistCreation></PlaylistCreation>
                            </Teleport>
                            <div class="flex flex-row items-center justify-self-end justify-end gap-x-2 ml-auto mr-2">
                                <button @click="togglePlaylistSelection(), formData.details.playlists = []" class="rounded-3xl w-[64px] h-[36px] bg-[#f2f2f2] hover:bg-[#e5e5e5]
                                     flex justify-center items-center justify-self-end ml-auto">
                                    <span>Cancel</span>
                                </button>
                                <button @click="togglePlaylistSelection" class="rounded-3xl w-[64px] h-[36px] bg-[#f2f2f2] hover:bg-[#e5e5e5]
                                     flex justify-center items-center justify-self-end ml-auto"
                                    :disabled="formData.details.playlists.length < 1"
                                    :class="[formData.details.playlists.length < 1 ? 'opacity-60' : '']">
                                    <span>Done</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="audience flex flex-col gap-y-2 mt-4">
                    <p class="text-[15px] font-medium">Audience</p>
                    <p class="text-[13px] font-medium">This video is set to made for kids Set by you</p>
                    <span class="text-[13px] font-normal text-gray-600">Regardless of your location, you're legally
                        required to comply with the Children's Online
                        Privacy Protection Act (COPPA) and/or other laws. You're required to tell us whether your
                        videos are made for kids.</span>

                    <div @click="formData.details.audience = 'kids', formData.details.audience = 'kids'"
                        class="flex flex-row gap-x-2 cursor-pointer">
                        <input v-model="formData.details.audience" :value="formData.details.audience"
                            :checked="formData.details.audience === 'kids'" name="audience-type" type="radio">
                        <p class="text-[15px] font-normal">Yes, it's made for kids</p>
                    </div>
                    <div @click="formData.details.audience = 'not-kids', formData.details.audience = 'not-kids'"
                        class="flex flex-row gap-x-2 cursor-pointer">
                        <input v-model="formData.details.audience" value="not-kids"
                            :checked="formData.details.audience === 'not-kids'" name="audience-type" type="radio">
                        <p class="text-[15px] font-normal">No, it's not made for kids </p>
                    </div>

                    <button @click="toggleAgeRestriction"
                        class="w-[209px] h-[48px] mt-4 flex flex-row items-center justify-start">
                        <img class="w-[12px] h-[12px] mr-2" :class="isAgeRestrictionOpen ? 'rotate-180' : ''"
                            :src="arrowDown" alt="">
                        <h3 class="text-[15px] font-medium">Age
                            restriction (advanced)</h3>
                    </button>
                    <div v-if="isAgeRestrictionOpen" class="accordion flex flex-col gap-y-2">
                        <p class="text-[13px] font-medium">Do you want to restrict your video to an adult
                            audience? </p>
                        <span class="text-[13px] font-normal">Age-restricted videos are not shown in certain
                            areas of YouTube. These videos may
                            have limited or no ads monetization.</span>
                        <div v-if="formData.details.audience === 'not-kids'" class="flex flex-col gap-y-2">
                            <div @click="formData.details.ageRestriction = 'yes'"
                                class="flex flex-row gap-x-2 cursor-pointer">
                                <input v-model="formData.details.ageRestriction" value="yes"
                                    :checked="formData.details.ageRestriction === 'yes'" class="radio"
                                    name="age-restriction" type="radio">
                                <p class="text-[15px] font-normal">Yes, restrict my video to viewers over 18 </p>
                            </div>
                            <div @click="formData.details.ageRestriction = 'no'"
                                class="flex flex-row gap-x-2 cursor-pointer">
                                <input v-model="formData.details.ageRestriction" value="no"
                                    :checked="formData.details.ageRestriction === 'no'" name="age-restriction"
                                    type="radio">
                                <p class="text-[15px] font-normal">No, don't restrict my video to viewers over 18
                                    only
                                </p>
                            </div>
                        </div>
                        <div v-else class="age-restriction-container flex flex-col gap-y-2">
                            <div class="flex flex-row gap-x-2 cursor-pointer opacity-80">
                                <input disabled class="radio" name="age-restriction" type="radio">
                                <p class="text-[15px] font-normal text-gray-400">Yes, restrict my video to viewers
                                    over
                                    18</p>
                            </div>
                            <div class="flex flex-row gap-x-2 cursor-pointer">
                                <input disabled checked name="age-restriction" type="radio">
                                <p class="text-[15px] font-normal text-gray-400">No, don't restrict my video to
                                    viewers
                                    over 18
                                    only
                                </p>
                            </div>
                            <div class="age-restriction-bar opacity-0 invisible w-[392px] h-[72px]
                                 rounded-lg shadow-outer">
                                <p class="text-[13px] font-normal pt-2 pl-2">
                                    This question is disabled because this video is set as made for kids.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="language flex flex-col gap-y-2 mt-4">
                    <h3 class="text-[15px] font-medium">Language</h3>
                    <p class="text-[13px] font-normal text-gray-600">
                        Select your video`s language (Optional)
                    </p>
                    <select v-model="formData.details.language"
                        class="w-[260px] h-[56px] rounded-lg border bg-white pl-2 text-[15px] font-normal"
                        name="language">
                        <option selected value="not-applicable" class="w-[252px] h-[32px] text-[15px] font-normal pl-2">
                            Not applicable
                        </option>
                        <option value="english" class="w-[252px] h-[32px] text-[15px] font-normal pl-2">
                            English (United States)
                        </option>
                        <option value="persian" class="w-[252px] h-[32px] text-[15px] font-normal pl-2">
                            Persian
                        </option>
                        <option value="hindu" class="w-[252px] h-[32px] text-[15px] font-normal pl-2">
                            Hindu
                        </option>
                    </select>
                </div>
                <div class="flex flex-col gap-y-2 mt-4 mb-10">
                    <h3 class="text-[15px] font-medium">Monetization</h3>
                    <p class="text-[13px] font-normal text-gray-600">
                        If you accept this, ads will be shown, and your video will be monetized.
                    </p>
                    <div class="flex flex-row  gap-x-4">
                        <input v-model="formData.details.monetized" type="checkbox">
                        <p class="text-[13px] font-normal text-gray-600">I ACCEPT that my video will be monetized
                            (your acceptance of the monetization of your video)</p>
                    </div>
                </div>
            </div>
            <div class="video-container sticky top-10 left-10 flex flex-col w-[304px] h-[350px]
                 rounded-lg bg-[#f9f9f9]">
                <div class="video-itself z-10 relative w-[304px] max-w-[304px] min-h-[171px] h-[171px] rounded-t-lg
                     overflow-hidden">
                    <video :volume="defaultVideoVolume" ref="videoRef" :muted="isVideoMuted"
                        class="w-full h-full object-cover" src="@/assets/video/test-vid2.mp4"></video>
                    <div
                        class="bg-transparent z-20 video-timeline absolute bottom-10 flex justify-center items-center pl-2">
                        <div ref="videoTimeTracker" class="select-none justify-center items-center absolute bottom-7 h-5
                             w-8 rounded-[4px] bg-black bg-opacity-80 text-white text-[12px] font-normal"
                            :style="{ left: `${trackerPosition}px`, display: videoTimeTrackerDisplay }">
                            {{ currentTimeLabel }}
                        </div>
                        <input @mouseenter="videoTimeTrackerDisplay = 'flex'" @mousemove="updateTimeLabel"
                            @mouseout="currentTimeLabel = '0:00', videoTimeTrackerDisplay = 'none'"
                            :value="videoCurrentTimePercentage" @input="videoUpdate" min="0" max="100"
                            class="video-time-tracker w-[280px] justify-self-center" type="range">
                    </div>
                    <div
                        class="video-control-bar bg-transparent z-20 w-full h-[40px] flex flex-row absolute bottom-0 items-center">
                        <div class="left-side-buttons flex justify-start items-center w-[70%] gap-x-2 pl-2
                             h-full justify-self-start">
                            <button @click=toggleVideoPlay class="w-[24px] h-[24px] flex justify-center items-center
                                 rounded-full">
                                <img class="w-[15px] h-[15px]" :src="isVideoPlayed ? pauseIcon : playIcon" alt="">
                            </button>
                            <button @click="toggleVideoMute" class="w-[24px] h-[24px] flex justify-center items-center
                                 rounded-full">
                                <img class="w-[20px] h-[20px]"
                                    :src="isVideoMuted || defaultVideoVolume <= 0 ? muteSpeakerIcon : fullSpeakerIcon"
                                    alt="">
                            </button>
                            <input @input="changeVideoVolume" min="0" max="10" :value="defaultVideoVolume * 10"
                                class="video-volume-input w-[32px] h-[32px]" type="range">
                            <p class="text-[14px] font-normal text-white">
                                <span class="video-current-time">{{ video_current_label }}</span>
                                /
                                <span class="video-end-time">{{ video_end_label }}</span>
                            </p>
                        </div>
                        <div class="right-side-buttons justify-self-end ml-auto mr-2">
                            <button @click="toggleVideoFullscreen"
                                class="w-[24px] h-[24px] flex justify-center items-center rounded-full">
                                <img class="w-[20px] h-[20px]" :src="fullScreenIcon" alt="">
                            </button>
                        </div>
                    </div>
                </div>
                <div class="flex flex-col font-normal mt-4 pl-2 pb-2">
                    <span class="text-[12px] text-gray-600">Video link</span>
                    <a href="#" class="text-[15px] text-[#2874d9]">https://youtube/sd40pNETAXQ</a>
                    <button
                        class="w-[39.2px] h-[39.2px] justify-self-end ml-auto rounded-full hover:bg-[#b8b2b2] flex justify-center items-center">
                        <img class="w-[20px] h-[20px]" :src="clipboardIcon" alt="">
                    </button>
                    <span class="text-[12px] text-gray-600 mt-6">Filename</span>
                    <a href="#" class="text-[15px]">redmagic-video.mp4</a>
                </div>
            </div>
        </div>
    </div>
</template>
<style scoped>
.age-restriction-bar {
    visibility: hidden;
    max-height: 0px;
}

.age-restriction-container:hover .age-restriction-bar {
    visibility: visible;
    transition: opacity 0.1s ease-in-out;
    opacity: 1;
    max-height: 72px;
}

.video-time-tracker::-moz-range-progress {
    height: 5px;
    background-color: #ff0033;
}

.video-time-tracker::-moz-range-thumb {
    background-color: #ff0033;
    width: 14px;
    height: 14px;
}

.video-time-tracker::-moz-range-track {
    height: 5px;
    background-color: black;
}

.video-volume-input::-moz-range-thumb {
    width: 12px;
    height: 12px;
}

@media (max-width: 740px) {
    .middle-section {
        display: none;
    }
}

.playlist-creation {
    box-shadow: 0 0 14px rgba(0, 0, 0, 0.15);
}

textarea {
    resize: none;
}

.stepper-div button {
    margin-right: 45px;
}

.video-listbox {
    box-shadow: 0 0 12px rgba(0, 0, 0, 0.13);
}

.upload-div {
    box-shadow: 0 0 14px rgba(0, 0, 0, 0.15);
}
</style>