"""I changed the user_log_info to user

Revision ID: 09b06cd56f2a
Revises: f75dcd1e07c7
Create Date: 2024-12-20 03:24:07.781886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b06cd56f2a'
down_revision: Union[str, None] = 'f75dcd1e07c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
