"""empty message

Revision ID: 30d6a55515d7
Revises: 7c2133313a2a
Create Date: 2024-12-25 04:50:47.242487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d6a55515d7'
down_revision: Union[str, None] = '7c2133313a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('playlists', sa.Column('visibility', sa.String(length=10), nullable=True))
    op.alter_column('playlists', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('playlists', 'visibility')
    op.drop_column('playlists', 'description')
    # ### end Alembic commands ###
