"""I added is_default

Revision ID: 452ad560b7fd
Revises: 15b0a42a3d19
Create Date: 2025-01-20 14:34:37.111570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '452ad560b7fd'
down_revision: Union[str, None] = '15b0a42a3d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "playlists",
        sa.Column(
            "is_default",
            sa.Boolean(),
            server_default="false",  # Default value for existing rows
            nullable=False,
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass