"""empty message

Revision ID: 470611f3a82f
Revises: f621fcf3dc16
Create Date: 2025-01-06 19:00:08.199077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470611f3a82f'
down_revision: Union[str, None] = 'f621fcf3dc16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'receiver_id')
    op.drop_column('notifications', 'sender_id')
    # ### end Alembic commands ###
