"""empty message

Revision ID: 6686777f4923
Revises: d0a8cf042c35
Create Date: 2025-01-06 18:51:05.735448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6686777f4923'
down_revision: Union[str, None] = 'd0a8cf042c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment_id')
    # ### end Alembic commands ###
