"""empty message

Revision ID: 67abbf634fbb
Revises: 30d6a55515d7
Create Date: 2024-12-26 01:58:58.231534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67abbf634fbb'
down_revision: Union[str, None] = '30d6a55515d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'videos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'user_id')
    # ### end Alembic commands ###
