"""empty message

Revision ID: f621fcf3dc16
Revises: 6686777f4923
Create Date: 2025-01-06 18:51:54.095456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f621fcf3dc16'
down_revision: Union[str, None] = '6686777f4923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment_id')
    op.add_column('notifications', sa.Column('comment_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'comment_id')
    op.add_column('comments', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
