"""empty message

Revision ID: f774a594cdea
Revises: 08ddfd84617b
Create Date: 2024-12-24 06:06:02.405707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f774a594cdea'
down_revision: Union[str, None] = '08ddfd84617b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserTestModels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserTestModels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='UserTestModels_pkey')
    )
    # ### end Alembic commands ###
