"""empty message

Revision ID: f7a973e5b215
Revises: a5b5da8f76fa
Create Date: 2025-01-07 09:56:27.017863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a973e5b215'
down_revision: Union[str, None] = 'a5b5da8f76fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_like_video_id_fkey', 'comments_like', type_='foreignkey')
    op.drop_column('comments_like', 'video_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments_like', sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_like_video_id_fkey', 'comments_like', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
