<script setup>
import { ref, computed } from 'vue'
import PlaylistCreation from './video_creation/PlaylistCreation.vue'
import { sharedState } from '@/sharedState'; // Shared states (aka global variables)

// Icons
import hamburgerBtn from '/src/assets/icons/svg-icons/collapse-menu-icon.svg'
import ytLogo from '/src/assets/img/yt-studio-logo.svg'
import searchIcon from '/src/assets/icons/svg-icons/search-icon.svg'
import createVideo from '/src/assets/icons/svg-icons/create-video-icon.svg'
import channelProfile from '/src/assets/img/Ruby.png'
import uploadIcon from '/src/assets/icons/svg-icons/upload-icon.svg'
import postIcon from '/src/assets/icons/svg-icons/post-icon.svg'
import playlistIcon from '/src/assets/icons/svg-icons/playlist-icon-2.svg'
import closeIcon from '/src/assets/icons/svg-icons/close-icon2.svg'
import clipboardIcon from '/src/assets/icons/svg-icons/clipboard-icon.svg'
import autoGeneratedIcon from '/src/assets/icons/svg-icons/auto-generated-icon.svg'
import arrowDown from '/src/assets/icons/svg-icons/thin-chevron-arrow-bottom-icon.svg'

const isVideoListboxOpen = ref(false)
const toggleVideoList = () => isVideoListboxOpen.value = !isVideoListboxOpen.value


const isFileUploadBoxOpen = ref(false)
const toggleFileUploadBox = () => isFileUploadBoxOpen.value = !isFileUploadBoxOpen.value

const inputField = ref(null)
const openFileInput = () => {
    inputField.value.click()
}

const uploadFile = (event) => {
    console.log(event.target.value)
}

// Edit Video Title Management
const videoTitle = ref('')
const videoTitleLength = computed(() => videoTitle.value.length)

const videoTitleEdit = (event) => {
    videoTitle.value = event.target.value;
}
const userAbleToSave = computed(() => { // User can only save the information if the title`s length is equal or greater than 0
    return (videoTitle.value.length > 0 ? true : false)
})

// Edit Video Description Management
const videoDescription = ref('')
const videoDescriptionLength = computed(() => videoDescription.value.length)
const videoDescriptionEdit = (event) => {
    videoDescription.value = event.target.value;
}


// Playlist visibility options
const isPlaylistSelectionOpen = ref(false)
const togglePlaylistSelection = () => isPlaylistSelectionOpen.value = !isPlaylistSelectionOpen.value


// Managing playlist creation tab with sharedStates
const togglePlaylistCreation = () => {
    sharedState.isPlaylistCreationOpen = !sharedState.isPlaylistCreationOpen
}
</script>

<template>
    <header class="font-roboto flex flex-row w-full h-[63.2px] mx-auto bg-white z-50 fixed shadow-lg
     justify-start items-center">
        <div class="left-section w-[20%] h-full flex flex-row justify-start items-center pl-5">
            <button class="w-[43.2px] h-[43.2px] rounded-full hover:bg-[#f0f0f0] flex justify-center items-center mr-[16px]
             flex-shrink-0 flex-grow-0">
                <img class="w-[22px] h-[22px] flex-shrink-0 flex-grow-0" :src="hamburgerBtn" alt="">
            </button>
            <img class="w-[98.4px] min-w-[98.4px] h-[24px] cursor-pointer" :src="ytLogo" alt="">
        </div>
        <div class="middle-section w-[60%] h-full flex justify-center items-center flex-row">
            <div style="width: 60%;"
                class="bg-[#f1f1f1] flex justify-start items-center flex-row rounded-[20px] border border-transparent hover:border-black transition duration-75">
                <img class="w-[20px] h-[20px] mx-4" :src="searchIcon" alt="">
                <input class="bg-transparent w-full h-[40px] outline-none text-[15px] font-normal placeholder:font-normal placeholder:text-[15px]
                 placeholder:text-[#757577]" type="text" placeholder="Search across your channel">
            </div>
        </div>
        <div class="right-section relative w-[20%] h-full flex flex-row justify-self-end ml-auto justify-end
         items-center pr-6 gap-x-4">
            <button @click="toggleVideoList" class="flex-grow-0 flex-shrink-0 hover:bg-[#e5e5e5] flex flex-row justify-center items-center pl-1 gap-x-2
             w-[95px] h-[34px] rounded-3xl border border-gray-200">
                <img class="w-[20px] h-[20px]" :src="createVideo" alt="">
                <p class="text-[14px] font-medium">Create</p>
            </button>
            <div v-if="isVideoListboxOpen" class="video-listbox absolute gap-y-1 py-4 top-[49px] right-[74px] w-[182px] h-auto rounded-xl
             bg-white flex flex-col justify-start items-center">
                <div @click="toggleFileUploadBox"
                    class="cursor-pointer w-full h-[32px] flex justify-start items-center hover:bg-[#f9f9f9]">
                    <img class="w-[20px] h-[20px] mr-4 ml-4" :src="uploadIcon" alt="">
                    <span>Upload videos</span>
                </div>
                <div class="cursor-pointer w-full h-[32px] flex justify-start items-center hover:bg-[#f9f9f9]">
                    <img class="w-[20px] h-[20px] mr-4 ml-4" :src="postIcon" alt="">
                    <span>Create post</span>
                </div>
                <div class="cursor-pointer w-full h-[32px] flex justify-start items-center hover:bg-[#f9f9f9]">
                    <img class="w-[20px] h-[20px] mr-4 ml-4" :src="playlistIcon" alt="">
                    <span>New playlist</span>
                </div>
            </div>
            <img class="w-[32px] h-[32px] rounded-full cursor-pointer" :src="channelProfile" alt="">
        </div>
    </header>

    <!-- <div v-if="isFileUploadBoxOpen" class="upload-div font-roboto w-[960px] h-[634px] flex flex-col absolute top-[75px] right-[250px] bg-white z-50
     rounded-3xl">
        <div class="title-section flex flex-row items-center border-b w-full h-[60.8px]">
            <div class="justify-self-start mr-auto pl-8">
                <p class="title text-[20px] font-medium">Upload videos</p>
            </div>
            <div class="justify-self-end ml-auto pr-4">
                <button @click="toggleFileUploadBox"
                    class="w-[39.2px] h-[39.2px] rounded-full hover:bg-[#dfdfdf] flex justify-center items-center">
                    <img draggable="false" class="w-[15px] h-[15px]" :src="closeIcon" alt="">
                </button>
            </div>
        </div>
        <div class="upload-section flex flex-col justify-center items-center w-full h-[558.4px]">
            <button @click="openFileInput"
                class="w-[136px] h-[136px] rounded-full flex justify-center items-center bg-[#f9f9f9]">
                <img draggable="false" class="w-[40%] h-[40%]" :src="uploadIcon" alt="">
            </button>
            <input @change="uploadFile" ref="inputField" class="hidden" type="file">
            <p class="text-[15px] font-normal mt-8">Drag and drop video files to upload</p>
            <span class="text-[13px] font-normal mt-1 text-[#5f5d5d]">Your videos will be private until you publish
                them.</span>
            <button @click="openFileInput" class="cursor-pointer w-[101px] h-[36px] rounded-3xl mt-6 bg-black text-white text-[14px]
             font-medium hover:bg-opacity-80">Select files</button>
        </div>
    </div> -->
    <div class="upload-div font-roboto w-[960px] h-[634px] flex flex-col absolute top-[75px] right-[250px] bg-white z-50
     rounded-3xl">
        <div class="title-section flex flex-row items-center border-b w-full h-[60.8px]">
            <div class="justify-self-start mr-auto pl-8">
                <p class="title text-[20px] font-medium">video title</p>
            </div>
            <div class="justify-self-end items-center flex flex-row justify-end ml-auto pr-4">
                <div class="w-[105px] h-[20px] rounded-md text-[12px] font-medium px-2 bg-[#e5e5e5] text-black mr-2">
                    <p>Saved as private</p>
                </div>
                <button @click="toggleFileUploadBox"
                    class="w-[39.2px] h-[39.2px] rounded-full hover:bg-[#dfdfdf] flex justify-center items-center">
                    <img draggable="false" class="w-[15px] h-[15px]" :src="closeIcon" alt="">
                </button>
            </div>
        </div>
        <div class="stepper-div flex flex-row justify-center items-center w-full h-[80px] border-b">
            <button
                class="w-[128px] h-[64px] rounded-lg bg-white hover:bg-[#e5e5e5] flex justify-center items-start pt-2">
                <span class="font-medium text-[15px]">Details</span>
            </button>
            <button
                class="w-[128px] h-[64px] rounded-lg bg-white hover:bg-[#e5e5e5] flex justify-center items-start pt-2">
                <span class="font-medium text-[15px] text-[#69666a]">Video elements</span>
            </button>
            <button
                class="w-[128px] h-[64px] rounded-lg bg-white hover:bg-[#e5e5e5] flex justify-center items-start pt-2">
                <span class="font-medium text-[15px] text-[#69666a]">Checks</span>
            </button>
            <button
                class="w-[128px] h-[64px] rounded-lg bg-white hover:bg-[#e5e5e5] flex justify-center items-start pt-2">
                <span class="font-medium text-[15px] text-[#69666a]">Visibility</span>
            </button>
        </div>

        <div style="scrollbar-width: thin;" class="video-metadata-editor w-full min-h-[433.6px] h-auto flex
         flex-col pl-[50px] overflow-y-auto overflow-x-hidden">
            <div class="editor-title-header w-full h-[32px] mt-2 mb-4">
                <h1 class="text-[25px] font-semibold">Details</h1>
            </div>
            <div class="flex flex-row">
                <div class="flex flex-col h-auto">
                    <div class="w-[536px] h-[79px] rounded-lg border border-solid border-[#d6d6d6] hover:border-black hover:border-2
                             focus:border-2 relative pl-2 pt-2 flex flex-col mb-8"
                        :style="{ borderColor: userAbleToSave ? 'black' : 'red', borderWidth: !userAbleToSave ? '2px' : '1px' }">
                        <span class="text-[12px] font-medium text-gray-600">Title (required)</span>
                        <textarea @input="videoTitleEdit" v-model="videoTitle"
                            class="mt-1 edit-title-input w-[440px] h-[41px] outline-none text-[15px] font-normal overflow-hidden leading-4"
                            placeholder="Add title" minlength="1" required maxlength="100"></textarea>
                        <span class="text-[12px] font-normal absolute right-1 bottom-1 text-gray-700"><span
                                class="title-char-counter">{{ videoTitleLength }}</span>/100</span>
                    </div>
                    <div class="w-[536px] flex flex-col max-w-[536px] relative h-[163px] max-h-[163px] rounded-lg
             border border-[#d6d6d6] pl-2 pt-2 hover:border-black hover:border-2">
                        <span class="text-[12px] font-medium text-gray-600">Description</span>
                        <textarea style="scrollbar-width: thin;" @input="videoDescriptionEdit"
                            v-model="videoDescription"
                            class="mt-1 edit-title-input w-[440px] h-[151px] outline-none text-[15px] font-normal overflow-y-auto leading-4"
                            placeholder="Add description" maxlength="5000"></textarea>
                        <span class="text-[12px] font-normal absolute right-1 bottom-1 text-gray-700"><span
                                class="title-char-counter">{{ videoDescriptionLength }}</span>/5000</span>
                    </div>
                    <div class="thumbnail-generator flex flex-col gap-y-1 mt-4">
                        <p class="text-[15px] font-medium">Thumbnail</p>
                        <span class="text-[13px] font-normal text-gray-600">Set a thumbnail that stands out and draws
                            viewers' attention.</span>
                        <div class="flex flex-row gap-x-4">
                            <button
                                class="w-[151px] h-[82px] rounded-sm border-dotted cursor-pointer hover:border-black border-2 flex justify-center items-center flex-col gap-y-2">
                                <img class="w-[18px] h-[18px]" :src="uploadIcon" alt="">
                                <span class="text-[12px] font-normal">Upload file</span>
                            </button>
                            <button
                                class="w-[151px] h-[82px] rounded-sm border-dotted cursor-pointer hover:border-black border-2 flex justify-center items-center flex-col gap-y-2">
                                <img class="w-[18px] h-[18px]" :src="autoGeneratedIcon" alt="">
                                <span class="text-[12px] font-normal">Auto-generated</span>
                            </button>
                        </div>
                    </div>

                    <div class="playlist-division flex flex-col gap-y-2 mt-4">
                        <p class="text-[15px] font-medium">Playlists</p>
                        <span class="text-[13px] font-normal text-gray-600">Add your video to one or more playlists to
                            organize your content for viewers.</span>
                        <div @click="togglePlaylistSelection" class="z-0 w-[260px] h-[48px] rounded-lg border hover:border-black bg-white text-[15px]
                        font-normal relative cursor-pointer text-gray-600 pl-3 flex justify-start items-center">
                            <p>Select</p>
                            <button class="w-[12px] h-[12px] justify-self-end ml-auto mr-3">
                                <img class="w-full h-full" :src="arrowDown" alt="">
                            </button>
                        </div>
                        <div v-if="isPlaylistSelectionOpen || sharedState.isPlaylistCreationOpen" class="absolute bottom-0 left-60
                             bg-white z-10 w-[397px] h-[389px] rounded-xl"
                            style="box-shadow: 0 0 10px rgba(0, 0, 0, 0.135);">
                            <div class="checkbox-group w-full h-[336px] justify-start items-center">
                            </div>
                            <div class="action-buttons w-full h-[52.8px] text-black flex flex-row text-[14px] font-medium
                                 px-2 border-t items-center">
                                <button @click="togglePlaylistCreation"
                                    class="rounded-3xl w-[120px] h-[36px] bg-[#f2f2f2] hover:bg-[#e5e5e5] flex justify-center items-center">
                                    <span>Create playlist</span>
                                </button>
                                <Teleport to="body">
                                    <PlaylistCreation v-if="sharedState.isPlaylistCreationOpen"></PlaylistCreation>
                                </Teleport>
                                <button class="rounded-3xl w-[64px] h-[36px] bg-[#f2f2f2] hover:bg-[#e5e5e5]
                                     flex justify-center items-center justify-self-end ml-auto">
                                    <span>Done</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="video-container flex flex-col w-[304px] h-[317px] rounded-lg ml-6 bg-[#f9f9f9]">
                    <div class="video-itself w-[304px] max-w-[304px] h-[171px] rounded-lg overflow-hidden">
                        <video class="w-full h-full object-cover" src="@/assets/video/test-vid2.mp4"></video>
                    </div>
                    <div class="flex flex-col font-normal mt-4 pl-2 pb-2">
                        <span class="text-[12px] text-gray-600">Video link</span>
                        <a href="#" class="text-[15px] text-[#2874d9]">https://youtube/sd40pNETAXQ</a>
                        <button
                            class="w-[39.2px] h-[39.2px] justify-self-end ml-auto rounded-full hover:bg-[#b8b2b2] flex justify-center items-center">
                            <img class="w-[20px] h-[20px]" :src="clipboardIcon" alt="">
                        </button>

                        <span class="text-[12px] text-gray-600 mt-6">Filename</span>
                        <a href="#" class="text-[15px]">redmagic-video.mp4</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- <PlaylistCreation v-if="false"></PlaylistCreation> -->
</template>
<style scoped>
@media (max-width: 740px) {
    .middle-section {
        display: none;
    }
}

.playlist-creation {
    box-shadow: 0 0 14px rgba(0, 0, 0, 0.15);
}

textarea {
    resize: none;
}

.stepper-div button {
    margin-right: 45px;
}

.video-listbox {
    box-shadow: 0 0 12px rgba(0, 0, 0, 0.13);
}

.upload-div {
    box-shadow: 0 0 14px rgba(0, 0, 0, 0.15);
}
</style>